services: 
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bandify_webserver
    ports:
      - 80:80
    volumes:
      - ./src/public:/var/www/html/
    links:
      - mysqldb

  mysqldb:
    image: mysql:latest
    container_name: bandify_db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql
